"""Argv-shaping invariants for :class:`MTProxyOrigResponder`.

The original Telegram MTProxy (C) binary's ``-S`` option insists on
exactly 32 hex digits — passing the operator-visible ``dd<32-hex>``
form makes the engine print ``'S' option requires exactly 32 hex
digits`` and exit 107. Censprobe's credential generator stores the
``dd``-prefixed form because clients need that prefix as the
obfuscated2 transport-tag. The responder is therefore responsible for
stripping the prefix at the argv boundary; this test guards that.
"""

from __future__ import annotations

import pytest
from censprobe_listener.mtproto_orig_responder import MTProxyOrigResponder


@pytest.mark.parametrize(
    ("secret_in", "expected_argv_secret"),
    [
        # The form actually generated by credentials.py: dd + 32 hex.
        ("dd" + "0123456789abcdef" * 2, "0123456789abcdef" * 2),
        # Operator overrides may use bare 32-hex form — pass through unchanged.
        ("0123456789abcdef" * 2, "0123456789abcdef" * 2),
        # Uppercase tolerated; normalised to lowercase so argv is canonical.
        ("DD" + "AABBCCDDEEFF0011" * 2, "aabbccddeeff0011" * 2),
    ],
)
def test_secret_for_argv_strips_dd_prefix(secret_in: str, expected_argv_secret: str) -> None:
    r = MTProxyOrigResponder(port=2080, secret=secret_in)
    # Operator-visible form preserved verbatim — the dashboard / handoff
    # depends on it (clients need the dd-prefixed string for obfuscated2).
    assert r.secret == secret_in
    # Argv form is exactly what the C binary's "-S" wants: 32 hex digits.
    assert r._secret_for_argv == expected_argv_secret
    assert len(r._secret_for_argv) == 32


def test_iptables_counter_rule_args_match_psh_ack_on_sport() -> None:
    """The OUTPUT counter rule must match data segments the proxy
    emits and nothing else.

    Specifically:
      * ``-p tcp`` so non-TCP traffic isn't counted.
      * ``--sport <port>`` so only the proxy's own outbound packets
        count (--dport would count inbound segments, which never have
        PSH set during a successful handshake the way we measure).
      * ``--tcp-flags PSH,ACK PSH,ACK`` — bare ACK / SYN-ACK / FIN /
        RST control segments are skipped; only data-bearing
        PSH+ACK segments tick the counter.
      * A unique comment so multiple responders / leftover rules
        across listener restarts can be discriminated.
    """
    r = MTProxyOrigResponder(port=2080, secret="dd" + "0123456789abcdef" * 2)
    args = r._counter_rule_args()
    assert "-p" in args and "tcp" in args
    assert "--sport" in args
    assert "2080" in args
    # The match arg pair appears in order.
    flag_idx = args.index("--tcp-flags")
    assert args[flag_idx + 1] == "PSH,ACK"
    assert args[flag_idx + 2] == "PSH,ACK"
    # Comment is per-port so two responders don't share a counter.
    assert r._counter_comment.endswith("-2080")
    assert "censprobe-mtorig" in r._counter_comment
    assert r._counter_comment in args


def test_per_port_counter_comments_are_unique() -> None:
    a = MTProxyOrigResponder(port=2080, secret="dd" + "00" * 16)
    b = MTProxyOrigResponder(port=4080, secret="dd" + "11" * 16)
    assert a._counter_comment != b._counter_comment


class TestStartSkipsWhenAllUpstreamsUnreachable:
    """Regression for the auth_cluster reconnect-storm bug.

    When proxy-multi.conf's upstream Telegram IPs are all unreachable
    (the typical RU-vantage case behind ТСПУ), launching mtproto-proxy
    triggers ~145 connect/s reconnect storm that starves accept() and
    produces every session as false BLOCKED. start() MUST detect this
    via probe_all_proxy_multi_upstreams + skip the subprocess spawn.
    """

    @pytest.mark.asyncio
    async def test_start_does_not_spawn_when_zero_alive(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        import censprobe_listener.mtproto_orig_responder as mod

        async def _all_dead(*_a: object, **_kw: object) -> tuple[list, list]:  # type: ignore[type-arg]
            return [], [("1.2.3.4", 8888, "1"), ("5.6.7.8", 8888, "2")]

        spawn_calls: list[object] = []

        async def _fake_spawn(*args: object, **kwargs: object) -> object:
            spawn_calls.append(args)
            raise AssertionError("subprocess MUST NOT be spawned when 0 alive")

        monkeypatch.setattr(mod, "probe_all_proxy_multi_upstreams", _all_dead)
        monkeypatch.setattr(mod.asyncio, "create_subprocess_exec", _fake_spawn)

        r = MTProxyOrigResponder(port=2080, secret="dd" + "00" * 16)
        await r.start()
        assert r.unavailable is True
        assert r.upstream_alive_count == 0
        assert r.upstream_total_count == 2
        assert spawn_calls == []
        assert r.is_running is False  # mirrors the unavailable state

    @pytest.mark.asyncio
    async def test_start_does_not_spawn_when_conf_missing(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # Image built without the mtproxy-orig stage: probe returns
        # ([], []) (empty total). Different diagnostic shape — the
        # operator's fix is "rebuild the image", not "use a different
        # vantage" — but the responder's behaviour is the same: skip
        # subprocess spawn, mark unavailable.
        import censprobe_listener.mtproto_orig_responder as mod

        async def _empty(*_a: object, **_kw: object) -> tuple[list, list]:  # type: ignore[type-arg]
            return [], []

        async def _fail_spawn(*args: object, **kwargs: object) -> object:
            raise AssertionError("subprocess MUST NOT be spawned when conf missing")

        monkeypatch.setattr(mod, "probe_all_proxy_multi_upstreams", _empty)
        monkeypatch.setattr(mod.asyncio, "create_subprocess_exec", _fail_spawn)

        r = MTProxyOrigResponder(port=2080, secret="dd" + "00" * 16)
        await r.start()
        assert r.unavailable is True
        assert r.upstream_total_count == 0
        assert r.is_running is False

    @pytest.mark.asyncio
    async def test_start_reuses_preflight_upstream_probe(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # When the listener threads in a preflight UpstreamProbe, start()
        # MUST reuse it and NOT re-probe proxy-multi.conf — the preflight
        # signal and the prune then derive from one measurement (no
        # sample-vs-full split, no TOCTOU re-probe).
        import censprobe_listener.mtproto_orig_responder as mod
        from censprobe_listener.preflight import UpstreamProbe

        async def _must_not_probe(*_a: object, **_kw: object) -> tuple[list, list]:  # type: ignore[type-arg]
            raise AssertionError("start() MUST reuse upstream_probe, not re-probe")

        async def _fail_spawn(*args: object, **kwargs: object) -> object:
            raise AssertionError("subprocess MUST NOT be spawned when 0 alive")

        monkeypatch.setattr(mod, "probe_all_proxy_multi_upstreams", _must_not_probe)
        monkeypatch.setattr(mod.asyncio, "create_subprocess_exec", _fail_spawn)

        r = MTProxyOrigResponder(port=2080, secret="dd" + "00" * 16)
        # Preflight found 0/2 alive — the responder must skip the spawn
        # off the threaded-in probe without issuing its own SYNs.
        r.upstream_probe = UpstreamProbe(
            alive=[], unreachable=[("1.2.3.4", 8888, "1"), ("5.6.7.8", 8888, "2")]
        )
        await r.start()
        assert r.unavailable is True
        assert r.upstream_alive_count == 0
        assert r.upstream_total_count == 2
        assert r.is_running is False

    @pytest.mark.asyncio
    async def test_stop_is_noop_when_unavailable(self, monkeypatch: pytest.MonkeyPatch) -> None:
        # An unavailable responder never installed an iptables rule
        # and never spawned a subprocess. stop() MUST short-circuit
        # before touching either — otherwise we'd attempt to remove
        # a rule that doesn't exist (causing iptables ERROR spam) and
        # awaiting a None process.
        import censprobe_listener.mtproto_orig_responder as mod

        async def _all_dead(*_a: object, **_kw: object) -> tuple[list, list]:  # type: ignore[type-arg]
            return [], [("1.2.3.4", 8888, "1")]

        async def _fail_counter(*args: object, **kwargs: object) -> object:
            raise AssertionError("install_counter / remove_counter MUST NOT run")

        monkeypatch.setattr(mod, "probe_all_proxy_multi_upstreams", _all_dead)
        monkeypatch.setattr(mod, "install_counter", _fail_counter)
        monkeypatch.setattr(mod, "remove_counter", _fail_counter)

        r = MTProxyOrigResponder(port=2080, secret="dd" + "00" * 16)
        await r.start()
        # stop() should not touch counters and not error.
        await r.stop()
