"""Argv-shaping invariants for :class:`MTProxyOrigResponder`.

The original Telegram MTProxy (C) binary's ``-S`` option insists on
exactly 32 hex digits — passing the operator-visible ``dd<32-hex>``
form makes the engine print ``'S' option requires exactly 32 hex
digits`` and exit 107. Censprobe's credential generator stores the
``dd``-prefixed form because clients need that prefix as the
obfuscated2 transport-tag. The responder is therefore responsible for
stripping the prefix at the argv boundary; this test guards that.
"""

from __future__ import annotations

import pytest
from censprobe_listener.mtproto_orig_responder import MTProxyOrigResponder


@pytest.mark.parametrize(
    ("secret_in", "expected_argv_secret"),
    [
        # The form actually generated by credentials.py: dd + 32 hex.
        ("dd" + "0123456789abcdef" * 2, "0123456789abcdef" * 2),
        # Operator overrides may use bare 32-hex form — pass through unchanged.
        ("0123456789abcdef" * 2, "0123456789abcdef" * 2),
        # Uppercase tolerated; normalised to lowercase so argv is canonical.
        ("DD" + "AABBCCDDEEFF0011" * 2, "aabbccddeeff0011" * 2),
    ],
)
def test_secret_for_argv_strips_dd_prefix(secret_in: str, expected_argv_secret: str) -> None:
    r = MTProxyOrigResponder(port=2080, secret=secret_in)
    # Operator-visible form preserved verbatim — the dashboard / handoff
    # depends on it (clients need the dd-prefixed string for obfuscated2).
    assert r.secret == secret_in
    # Argv form is exactly what the C binary's "-S" wants: 32 hex digits.
    assert r._secret_for_argv == expected_argv_secret
    assert len(r._secret_for_argv) == 32
