created_at: '2026-05-13T20:09:47.956721Z'
planned_sessions: []
probe_core_version: 0.1.0
server:
  distro: Debian GNU/Linux 13 (trixie) 13
  endpoint:
    asn:
      asn: 44677
      descr: MTS-NGCLOUD-AS, RU
      domain: mts.ru
      org: MTS PJSC
      route: 171.22.72.0/22
    company:
      domain: mts.ru
      name: MTS PJSC
      network: 171.22.72.0 - 171.22.75.255
    datacenter: null
    is_datacenter: false
    is_mobile: false
    location:
      city: Moscow
      country_code: RU
  ipv6_available: false
  kernel: 6.8.0-106-generic
test_id: mts-runtime-review
